### ISSUE TITLE
Calling multiple server ID's in Matlab causes a ConcurrentModificationException

### ISSUE THREAD

**Issue by Max5254** [WPIRoboticsEngineering/RBE3001_Matlab#5]
When `pp.command(ID, packet);` is called with multiple server IDs in the same program the second call with throw an exception and communication will stop working. It will happen no matter which combination of servers are called. 

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at edu.wpi.SimplePacketComs.AbstractSimpleComsDevice$1.run(AbstractSimpleComsDevice.java:262)
```

**Comment by madhephaestus** [comment]
According to the source: https://github.com/madhephaestus/SimplePacketComsJava/blob/master/src/main/java/edu/wpi/SimplePacketComs/AbstractSimpleComsDevice.java#L262

that stack trace is caught, printed, then ignored. That line is also in the internal run thread, meaning it is out of execution critical path. Your description of behavior isn't producing the same result on my end. Try to add more detail as to how and when the communications fail, are you *sure* the packets stopped being sent to the arm? If so, how did you test that? Is it your matlab code failing out maybe?

**Comment by madhephaestus** [comment]
If you would like to try the latest version to see if that fixes your issue, you can replace your SImplePacketCommsJava jar file with the one from here: https://github.com/madhephaestus/SimplePacketComsJava/releases/tag/0.6.1(Be sure to change you Matlab reference, and restart matlab). If that fixes the issue for you please come back and comment here and close the issue.

**Comment by madhephaestus** [comment]
I have spent a few hours on this at this point, i can not reproduce your error with or without the update to the core library. If it persists until tuesday I can come in and take a look at your particular code and setup.

**Comment by MikaylaFischler** [comment]
Hi, I'm having the same issue as Max after using that new jar file. It no longer errors out, but neither of us can get any data back in the received packet, we just get all 0s. If I comment out the initial request for status and hard code some values to send, the calibration works properly.

**Comment by madhephaestus** [comment]
@MikaylaFischler please post a link to a commit containing your workaround so i can see what you are talking about.

**Comment by MikaylaFischler** [comment]
Here is the [current nucleo code](https://github.com/RBE300X-Lab/Team_02_NUCLEO/tree/lab1-dev).
The matlab code with the initial status requests is [here](https://github.com/RBE300X-Lab/Team_02_MATLAB/commit/d2411b394d795651cca39a02d6abb3780ad8a337) (this code fails to get a response from the nucleo, with or without the `pp.shutdown()` and pause).
The matlab code with no initial status requests and hard coded configuration positions is [here](https://github.com/RBE300X-Lab/Team_02_MATLAB/commit/7643b753f14236f741262602724ac590dab1085f) (this does get a response).

**Comment by madhephaestus** [comment]
hmmm, are you calling pp.shutdown() and then expecting to communicate? After thats called the hardware is disconnected and can't be reconnected without restarting the script. 

If thats not the issue, I would look more closely at the for loop around the send, the first send creates the packet, and it may not have been in the mailbox long enough for the sending thread to send the packet. Try a startup routine:

 * send the packet with values once
 * wait 10ms
 * then begin the fast polling.

**Comment by MikaylaFischler** [comment]
We had added the `pp.shutdown()` after it was already not working, hoping it could help, so that wasn't the initial issue. The 10ms delay (without the presence of `pp.shutdown()`) did fix the problem for my group.

**Comment by madhephaestus** [comment]
well, note that you must have pp.shutdown() at the end of the script, and all of your code must be in a try/catch, with pp.shutdown at the very end after the end of the catch statement. If you remove these features, you will not be able to talk to your arm more than once without restarting Matlab.

**Comment by madhephaestus** [comment]
I pushed a new version of the lib to the bugfix branch, it adds the 10ms startup delay to the first call of a command.

**Comment by madhephaestus** [comment]
If this is resolved please close the issue @Max5254

**Comment by nag92** [comment]
@Max5254  @MikaylaFischler  is this problem solved?
