### ISSUE TITLE
cannot run multiply servers 

### ISSUE THREAD

**Issue by nag92** [WPIRoboticsEngineering/RBE3001_Matlab#7]

**Comment by nag92** [comment]
@madhephaestus The branch "use_jar62" resolves this issue

**Comment by madhephaestus** [comment]
This is not nearly descriptive enough for an issue. 

Did you mean multiple? 
How was this tested, what did you validate working or not?

**Comment by nag92** [comment]
All the students were unable to get any data back using V6.3. All they got back were was 15 zeros. However 3 groups switched back to V6.2. With this release and wrapping the matlab code in "clear" they were able to run several servers and get data back that made sense

**Comment by madhephaestus** [comment]
I just pulled up the 6.3 version with 2 servers on my arm at home, it is communicating on both accounts. I can not reproduce the all zeros problem. Are you sure its not another code error? 
It seems like to me if they start a "zeroing out the link" server, then whatever value the link is at is set to zero. If this server is allowed to run forever, then what would happen is the PID server and all are running just fine, but with the link encoder constantly being reset to zero from the config server, then it would look like the motors shut off (the pid command is 0) the link is stuck at 0, the velocity is rightly calculated to 0 and the load cell ist hooked up yet, thus a packet of all 0's but in fact the full stack is working just fine. 

Are you *sure* that scenario, or something similar, isnt whats going on here?

**Comment by madhephaestus** [comment]
that said, i'll add an API hook for matlab to set up write packets as one shots. Ill put it in the bugfix branch.

**Comment by madhephaestus** [comment]
I just pushed to bugfix branch an updated coms jar and an extended PacketProcessor that includes a one-shot mode write() function. If you use that it will only send write packets of that command once per call of the function (assuming you wait for the packet to be transferred out of the mailbox). read() and command() set up polling packets and will initiate a continuous polling of a command with the most recent data in the mailbox.

**Comment by madhephaestus** [comment]
@nag92 can you pull my branch and check that the behavior reported above is corrected?
